import dayjs from 'dayjs';
import Head from 'next/head';
import React from 'react'
import { ActionButton } from '../components/Button/ActionButton';
import { HorizontalCalendar } from '../components/HorizontalCalendar/HorizontalCalendar';
import { PointCardList } from '../components/PointCard/PointCardList';
import styles from '../styles/Dashboard.module.scss';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import Link from 'next/link';
import { Header } from '../components/Header/Header';
import { useAppUser } from '../hooks/user';

interface DashboardPageProps{

}

const DashboardPage: React.FC<DashboardPageProps> = ({}) => {
  const {groupName} = useAppUser()

  const [date, setDate] = React.useState(dayjs().format('YYYY-MM-DD'));

  return (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <main className={styles.main}>
      <div className={styles.calendar_container}>
        <h1>{groupName || ''}</h1>
        <HorizontalCalendar selectedDay={date} onChange={setDate}/>
      </div>

      <PointCardList date={date}/>
    </main>

    <Link href="/new">
      <ActionButton>
        <span>+ Adicionar Exercício</span>
      </ActionButton>
    </Link>
  </div>
  );
}

export default withPageAuthRequired(DashboardPage);