import dayjs from 'dayjs';
import Head from 'next/head';
import React from 'react'
import { ActionButton } from '../components/Button/ActionButton';
import { HorizontalCalendar } from '../components/HorizontalCalendar/HorizontalCalendar';
import { PointCardList } from '../components/PointCard/PointCardList';
import styles from '../styles/Dashboard.module.scss';
import { withPageAuthRequired } from '@auth0/nextjs-auth0';
import Link from 'next/link';
import { Header } from '../components/Header/Header';

interface DashboardPageProps{

}

const DashboardPage: React.FC<DashboardPageProps> = ({}) => {
  return (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <main className={styles.main}>
      <div className={styles.calendar_container}>
        <h1>Projeto Verão</h1> {/* TODO - From Backend */}
        <HorizontalCalendar selectedDay={dayjs()}/>
      </div>

      <PointCardList />
    </main>

    <Link href="/new">
      <ActionButton>
        <span>+ Adicionar Exercício</span>
      </ActionButton>
    </Link>
  </div>
  );
}

export default withPageAuthRequired(DashboardPage);