import dayjs from 'dayjs';
import Head from 'next/head';
import React from 'react'
import { ActionButton } from '../components/Button/ActionButton';
import { HorizontalCalendar } from '../components/HorizontalCalendar/HorizontalCalendar';
import { PointCardList } from '../components/PointCard/PointCardList';
import styles from '../styles/Dashboard.module.scss';
import { FiMenu } from 'react-icons/fi'

interface DashboardPageProps{

}

const DashboardPage: React.FC<DashboardPageProps> = ({}) => {
  return (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <header className={styles.header}>
      <div className={styles.header__avatar}>
        <img 
          src={`https://avatars.dicebear.com/api/initials/${'Johane Doe'}.svg `}
          alt={`${'Johane Doe'} - avatar`} 
        />
      </div>
      <b className={styles.header__username}>Johane Doe</b>
      <button className={`highlight-text ${styles.menu__btn}`}>
        <FiMenu />
      </button>
    </header>

    <main className={styles.main}>
      <div className={styles.calendar_container}>
        <h1>Projeto Verão</h1> {/* TODO - From Backend */}
        <HorizontalCalendar selectedDay={dayjs()}/>
      </div>

      <PointCardList />
    </main>

    <ActionButton>
      <span>+ Adicionar Exercício</span>
    </ActionButton>
  </div>
  );
}

export default DashboardPage;