import dayjs from 'dayjs';
import Head from 'next/head';
import React from 'react'
import { ActionButton } from '../components/Button/ActionButton';
import { HorizontalCalendar } from '../components/HorizontalCalendar/HorizontalCalendar';
import { PointCardList } from '../components/PointCard/PointCardList';
import styles from '../styles/Dashboard.module.scss';
import { FiMenu } from 'react-icons/fi'
import { PointForm } from '../components/PointForm/PointForm';
import { Header } from '../components/Header/Header';

interface NewExerciseLogPageProps{

}

const NewExerciseLogPage: React.FC<NewExerciseLogPageProps> = ({}) => {
  return (
  <div className={styles.container}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Header />

    <main className={styles.main}>
      <PointForm id="new_exercise_log__form"/>
    </main>

    <ActionButton type="submit" form="new_exercise_log__form">
      <span>Salvar</span>
    </ActionButton>
  </div>
  );
}

export default NewExerciseLogPage;